import { regions } from "@/lib/regions";

export type { Region } from "@/lib/regions";
export type { Category } from "@/lib/categories";
export { regions } from "@/lib/regions";
export { categories } from "@/lib/categories";

export type Difficulty = "Easy" | "Moderate" | "Challenging" | "Strenuous";

export interface ItineraryDay {
  day: string;
  title: string;
  detail: string;
}

export interface Trek {
  slug: string;
  name: string;
  region: string;
  regionSlug: string;
  regionLabel: string;
  categorySlug: string;
  categoryLabel: string;
  tagline: string;
  heroImage: string;
  gallery: string[];
  duration: string;
  durationDays: number;
  maxAltitude: string;
  difficulty: Difficulty;
  bestSeason: string;
  groupSize: string;
  priceFrom: number;
  restrictedArea: boolean;
  shortDescription: string;
  overview: string;
  highlights: string[];
  permits: string[];
  itinerary: ItineraryDay[];
  included: string[];
  excluded: string[];
  faqs: { q: string; a: string }[];
}

export const treks: Trek[] = [
  {
    slug: "everest-base-camp-trek",
    name: "Everest Base Camp Trek",
    region: "Khumbu / Everest Region",
    regionSlug: "everest",
    regionLabel: "Everest Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "Stand beneath the roof of the world",
    heroImage: "/images/treks/everest-base-camp.jpg",
    gallery: [
      "/images/treks/everest-base-camp.jpg",
      "/images/treks/everest-base-camp-2.jpg",
      "/images/treks/everest-base-camp-3.jpg",
    ],
    duration: "14 Days",
    durationDays: 14,
    maxAltitude: "5,545 m / 18,192 ft (Kala Patthar)",
    difficulty: "Challenging",
    bestSeason: "March–May & September–November",
    groupSize: "2–12 (private trips available)",
    priceFrom: 1350,
    restrictedArea: false,
    shortDescription:
      "The classic Everest Base Camp Trek takes you through Sherpa villages, the Sagarmatha National Park, and up to Kala Patthar for the best close-up view of Mount Everest in the world.",
    overview:
      "The Everest Base Camp Trek is Nepal's most iconic walk — a 14-day journey from the thrilling mountain airstrip at Lukla through Namche Bazaar, Tengboche Monastery, and Dingboche to Everest Base Camp itself, with a sunrise climb to Kala Patthar for the finest panorama of Everest, Nuptse and Lhotse. Along the way you will pass through the heart of Sherpa culture, prayer-flag-strung suspension bridges, and some of the highest-altitude teahouses on earth. TrekVibe Nepal builds in proper acclimatization days at Namche Bazaar and Dingboche so trekkers of good fitness — not necessarily prior high-altitude experience — can comfortably reach EBC.",
    highlights: [
      "Sunrise views of Everest, Nuptse and Lhotse from Kala Patthar (5,545 m)",
      "Scenic mountain flight into Lukla, gateway to the Khumbu",
      "Namche Bazaar, the trading and cultural hub of the Sherpa people",
      "Tengboche Monastery with Ama Dablam as a backdrop",
      "Walking through Sagarmatha National Park, a UNESCO World Heritage Site",
      "Standing at Everest Base Camp (5,364 m) itself",
    ],
    permits: [
      "Sagarmatha National Park Entry Permit",
      "Khumbu Pasang Lhamu Rural Municipality Entry Permit",
    ],
    itinerary: [
      { day: "Day 1", title: "Arrive in Kathmandu", detail: "Airport pickup and transfer to hotel. Welcome briefing and gear check with your guide." },
      { day: "Day 2", title: "Fly to Lukla, trek to Phakding", detail: "Scenic 35-minute flight to Lukla (2,860 m); short trek to Phakding (2,610 m) along the Dudh Koshi river." },
      { day: "Day 3", title: "Trek to Namche Bazaar", detail: "Cross suspension bridges and climb steadily into Sagarmatha National Park to Namche Bazaar (3,440 m)." },
      { day: "Day 4", title: "Acclimatization in Namche", detail: "Day hike to Everest View Hotel or Khumjung village for first views of Everest; rest and acclimatize." },
      { day: "Day 5", title: "Trek to Tengboche", detail: "Walk to Tengboche (3,860 m), home to the region's most famous monastery, with views of Ama Dablam." },
      { day: "Day 6", title: "Trek to Dingboche", detail: "Descend through rhododendron forest and climb to the farming village of Dingboche (4,410 m)." },
      { day: "Day 7", title: "Acclimatization in Dingboche", detail: "Optional hike to Nangkartshang Peak viewpoint for acclimatization before continuing higher." },
      { day: "Day 8", title: "Trek to Lobuche", detail: "Walk past the Khumbu Glacier memorials to Lobuche (4,940 m)." },
      { day: "Day 9", title: "Trek to Gorak Shep & Everest Base Camp", detail: "Reach Gorak Shep (5,164 m), then continue to Everest Base Camp (5,364 m) before returning to Gorak Shep to sleep." },
      { day: "Day 10", title: "Kala Patthar sunrise, descend to Pheriche", detail: "Pre-dawn climb to Kala Patthar (5,545 m) for the best Everest panorama, then descend to Pheriche." },
      { day: "Day 11", title: "Trek to Namche Bazaar", detail: "Long descent back through Tengboche and Sanasa to Namche Bazaar." },
      { day: "Day 12", title: "Trek to Lukla", detail: "Final descent to Lukla, celebration dinner with your guide and porter team." },
      { day: "Day 13", title: "Fly to Kathmandu", detail: "Morning flight back to Kathmandu; free afternoon and evening at leisure." },
      { day: "Day 14", title: "Departure", detail: "Transfer to Tribhuvan International Airport for your onward flight." },
    ],
    included: [
      "Airport pickup and drop-off",
      "Kathmandu–Lukla–Kathmandu flights",
      "Government-licensed English-speaking trekking guide",
      "Porter service (1 porter per 2 trekkers)",
      "Teahouse accommodation during the trek",
      "All permits and TIMS card",
      "First-aid kit and pulse oximeter for daily oxygen checks",
    ],
    excluded: [
      "Nepal entry visa fee",
      "Travel insurance (mandatory, incl. helicopter evacuation cover)",
      "Meals in Kathmandu",
      "Personal trekking gear",
      "Tips for guide and porter",
    ],
    faqs: [
      { q: "How hard is the Everest Base Camp Trek for a beginner?", a: "EBC is graded challenging mainly due to altitude, not technical terrain. Trekkers with good general fitness and no prior high-altitude experience complete it regularly, provided the itinerary includes proper acclimatization days like ours." },
      { q: "What is the Everest Base Camp Trek cost?", a: "Our EBC packages start from USD 1,350 per person, including Lukla flights, a licensed guide, porter, teahouse stay and permits. Final cost depends on group size and season." },
      { q: "Do I need travel insurance for the Everest Base Camp Trek?", a: "Yes — insurance covering high-altitude trekking and helicopter evacuation up to 6,000 m is mandatory for all our Khumbu treks." },
    ],
  },
  {
    slug: "annapurna-base-camp-trek",
    name: "Annapurna Base Camp Trek",
    region: "Annapurna Region",
    regionSlug: "annapurna",
    regionLabel: "Annapurna Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "Into the sanctuary of the Annapurnas",
    heroImage: "/images/treks/annapurna-base-camp.jpg",
    gallery: ["/images/treks/annapurna-base-camp.jpg"],
    duration: "9 Days",
    durationDays: 9,
    maxAltitude: "4,130 m / 13,549 ft",
    difficulty: "Moderate",
    bestSeason: "March–May & September–December",
    groupSize: "2–12 (private trips available)",
    priceFrom: 750,
    restrictedArea: false,
    shortDescription:
      "Trek through rhododendron forests, terraced villages and glacial moraine into the natural amphitheatre of Annapurna Base Camp, ringed by 7,000 m and 8,000 m peaks.",
    overview:
      "The Annapurna Base Camp (ABC) Trek climbs from subtropical foothills near Pokhara through Gurung and Magar villages, dense rhododendron and bamboo forest, and finally onto glacial moraine that opens into the Annapurna Sanctuary — a natural bowl surrounded by Annapurna I (8,091 m), Machhapuchhre (Fishtail, 6,993 m) and Hiunchuli. It is shorter and less demanding than the Everest or Annapurna Circuit treks while still delivering true high-mountain scenery, which makes it one of our most popular treks for trekkers with limited time.",
    highlights: [
      "Sunrise over Annapurna I and Machhapuchhre from Base Camp",
      "Natural hot springs at Jhinu Danda to soothe tired legs",
      "Gurung and Magar villages with distinct Himalayan culture",
      "Dense rhododendron forest (spectacular March–April bloom)",
      "Shorter, moderate alternative to the full Annapurna Circuit",
    ],
    permits: ["Annapurna Conservation Area Permit (ACAP)", "TIMS Card"],
    itinerary: [
      { day: "Day 1", title: "Kathmandu to Pokhara", detail: "Drive or fly to Pokhara (820 m); relax by Phewa Lake." },
      { day: "Day 2", title: "Drive to Nayapul, trek to Tikhedhunga", detail: "Short drive to the trailhead at Nayapul, then trek to Tikhedhunga (1,540 m)." },
      { day: "Day 3", title: "Trek to Ghorepani", detail: "Climb through rhododendron forest to Ghorepani (2,860 m)." },
      { day: "Day 4", title: "Poon Hill sunrise, trek to Tadapani", detail: "Pre-dawn hike to Poon Hill (3,210 m) for Annapurna and Dhaulagiri views, then on to Tadapani." },
      { day: "Day 5", title: "Trek to Chhomrong", detail: "Descend and climb again to Chhomrong (2,170 m), gateway to the Sanctuary." },
      { day: "Day 6", title: "Trek to Himalaya/Deurali", detail: "Follow the Modi Khola gorge deep into the Sanctuary to Himalaya or Deurali (3,230 m)." },
      { day: "Day 7", title: "Trek to Annapurna Base Camp", detail: "Walk through Machhapuchhre Base Camp to reach Annapurna Base Camp (4,130 m) for sunset views." },
      { day: "Day 8", title: "Descend to Jhinu Danda", detail: "Long descent to Jhinu Danda (1,780 m); soak in the natural hot springs." },
      { day: "Day 9", title: "Trek to Nayapul, drive to Pokhara", detail: "Final descent to Nayapul and drive back to Pokhara." },
    ],
    included: [
      "Ground transport Pokhara–Nayapul–Pokhara",
      "Licensed English-speaking trekking guide",
      "Porter service",
      "Teahouse accommodation during the trek",
      "ACAP permit and TIMS card",
    ],
    excluded: ["Kathmandu–Pokhara transport", "Meals outside the trek", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "Can beginners do the Annapurna Base Camp Trek?", a: "Yes. ABC is graded moderate — trails are well maintained with teahouses throughout, and the maximum altitude of 4,130 m is far less demanding than Everest Base Camp or Annapurna Circuit." },
      { q: "Is Poon Hill included in the Annapurna Base Camp Trek?", a: "Our standard ABC route passes through Ghorepani, and we include the optional Poon Hill sunrise excursion at no extra cost." },
    ],
  },
  {
    slug: "langtang-valley-trek",
    name: "Langtang Valley Trek",
    region: "Langtang Region",
    regionSlug: "langtang",
    regionLabel: "Langtang Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "The Himalaya closest to Kathmandu",
    heroImage: "/images/treks/langtang.jpg",
    gallery: ["/images/treks/langtang.jpg"],
    duration: "8 Days",
    durationDays: 8,
    maxAltitude: "4,984 m / 16,352 ft (Tserko Ri)",
    difficulty: "Moderate",
    bestSeason: "March–May & September–November",
    groupSize: "2–12 (private trips available)",
    priceFrom: 700,
    restrictedArea: false,
    shortDescription:
      "Just a day's drive from Kathmandu, the Langtang Valley Trek combines glacier-lined peaks, Tamang villages and the Kyanjin Gompa monastery in one of Nepal's most underrated trekking regions.",
    overview:
      "The Langtang Valley Trek is the closest Himalayan trek to Kathmandu, following the Langtang Khola through pine and bamboo forest into a glacier-carved valley walled by 6,000–7,000 m peaks. The trail leads to Kyanjin Gompa, a working Buddhist monastery, with side trips to Tserko Ri or Kyanjin Ri viewpoints for sweeping views of Langtang Lirung (7,227 m). Rebuilt after the 2015 earthquake, the valley's Tamang communities are known for their warmth and distinct Tibetan-influenced culture, and trekking here also directly supports the local economy.",
    highlights: [
      "Kyanjin Gompa monastery and its yak-cheese factory",
      "Panoramic views from Tserko Ri or Kyanjin Ri",
      "Tamang villages and Tibetan Buddhist culture",
      "Langtang National Park glaciers and alpine meadows",
      "Only 7–8 hours' drive from Kathmandu — no domestic flight needed",
    ],
    permits: ["Langtang National Park Entry Permit", "TIMS Card"],
    itinerary: [
      { day: "Day 1", title: "Drive Kathmandu to Syabrubesi", detail: "Scenic 7–8 hour drive along the Trishuli river to Syabrubesi (1,550 m)." },
      { day: "Day 2", title: "Trek to Lama Hotel", detail: "Follow the Langtang Khola through forest to Lama Hotel (2,470 m)." },
      { day: "Day 3", title: "Trek to Langtang Village", detail: "Climb through rebuilt villages with valley views to Langtang Village (3,430 m)." },
      { day: "Day 4", title: "Trek to Kyanjin Gompa", detail: "Short, scenic walk to Kyanjin Gompa (3,870 m); visit the monastery and cheese factory." },
      { day: "Day 5", title: "Acclimatization: Tserko Ri or Kyanjin Ri", detail: "Optional climb to Tserko Ri (4,984 m) or the easier Kyanjin Ri for panoramic mountain views." },
      { day: "Day 6", title: "Trek back to Lama Hotel", detail: "Retrace the trail downhill through forest back to Lama Hotel." },
      { day: "Day 7", title: "Trek to Syabrubesi", detail: "Final descent to Syabrubesi." },
      { day: "Day 8", title: "Drive back to Kathmandu", detail: "Return drive to Kathmandu." },
    ],
    included: ["Kathmandu–Syabrubesi–Kathmandu ground transport", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits"],
    excluded: ["Meals in Kathmandu", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "Is the Langtang Trek good for a short holiday?", a: "Yes — at 8 days including drive time from Kathmandu, Langtang is one of the most time-efficient Himalayan treks, ideal if you have limited leave but still want big-mountain scenery." },
    ],
  },
  {
    slug: "gosaikunda-lake-trek",
    name: "Gosaikunda Lake Trek",
    region: "Langtang / Rasuwa Region",
    regionSlug: "langtang",
    regionLabel: "Langtang Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "A sacred alpine lake in the clouds",
    heroImage: "/images/treks/gosaikunda.jpg",
    gallery: ["/images/treks/gosaikunda.jpg"],
    duration: "7 Days",
    durationDays: 7,
    maxAltitude: "4,610 m / 15,124 ft (Laurebina Pass)",
    difficulty: "Challenging",
    bestSeason: "March–May, September–November & August (Janai Purnima)",
    groupSize: "2–12 (private trips available)",
    priceFrom: 650,
    restrictedArea: false,
    shortDescription:
      "A pilgrimage and trekking trail to Gosaikunda, a sacred glacial lake at 4,380 m, crossing the high Laurebina Pass through rhododendron forest and alpine meadow.",
    overview:
      "Gosaikunda is one of the holiest lakes in Hindu mythology, believed to have been created by Lord Shiva, and thousands of pilgrims visit during the Janai Purnima festival each August. As a trek, the route climbs steeply from Dhunche through dense forest and rhododendron groves to the alpine lake district, then crosses the wind-swept Laurebina Pass (4,610 m) — making it a genuinely high-altitude experience in a shorter time frame than most Himalayan treks. It can also be combined with the Langtang Valley or Helambu treks for a longer circuit.",
    highlights: [
      "Gosaikunda, a sacred high-altitude lake at 4,380 m",
      "Crossing Laurebina Pass (4,610 m)",
      "Rhododendron and oak forest en route",
      "Can be combined with Langtang or Helambu for a longer trek",
      "Rich Hindu and Buddhist pilgrimage significance",
    ],
    permits: ["Langtang National Park Entry Permit", "TIMS Card"],
    itinerary: [
      { day: "Day 1", title: "Drive Kathmandu to Dhunche", detail: "6–7 hour drive to Dhunche (1,960 m), entry point to Langtang National Park." },
      { day: "Day 2", title: "Trek to Sing Gompa", detail: "Climb through forest to Sing Gompa (3,330 m), home to a cheese factory and monastery." },
      { day: "Day 3", title: "Trek to Gosaikunda", detail: "Ascend past alpine lakes to Gosaikunda (4,380 m)." },
      { day: "Day 4", title: "Cross Laurebina Pass to Ghopte", detail: "Cross the high Laurebina Pass (4,610 m) and descend to Ghopte." },
      { day: "Day 5", title: "Trek to Kutumsang", detail: "Descend through forest and ridge trail to Kutumsang." },
      { day: "Day 6", title: "Trek to Chisapani", detail: "Continue on the Helambu ridge trail to Chisapani, with Kathmandu Valley views." },
      { day: "Day 7", title: "Trek to Sundarijal, drive to Kathmandu", detail: "Final descent to Sundarijal and drive back into Kathmandu." },
    ],
    included: ["Kathmandu–Dhunche ground transport", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits"],
    excluded: ["Meals in Kathmandu", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "Is Gosaikunda a good trek for pilgrimage travelers?", a: "Very much so — many of our guests combine the trek with Hindu pilgrimage rituals at the lake, especially during the Janai Purnima full moon festival in August." },
    ],
  },
  {
    slug: "ghorepani-poon-hill-trek",
    name: "Ghorepani Poon Hill Trek",
    region: "Annapurna Region",
    regionSlug: "annapurna",
    regionLabel: "Annapurna Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "Nepal's best short sunrise trek",
    heroImage: "/images/treks/mardi-himal.jpg",
    gallery: ["/images/treks/mardi-himal.jpg"],
    duration: "5 Days",
    durationDays: 5,
    maxAltitude: "3,210 m / 10,531 ft",
    difficulty: "Easy",
    bestSeason: "Year-round; best March–May & September–November",
    groupSize: "2–14 (great for families)",
    priceFrom: 450,
    restrictedArea: false,
    shortDescription:
      "A short, family-friendly trek through rhododendron forest and hillside villages to the famous Poon Hill viewpoint, with sunrise views over the Annapurna and Dhaulagiri ranges.",
    overview:
      "The Ghorepani Poon Hill Trek is Nepal's most popular short trek — a 5-day route from Nayapul through Gurung and Magar villages and thick rhododendron forest to Ghorepani, from where a pre-dawn climb up Poon Hill (3,210 m) rewards you with one of the widest mountain panoramas in Nepal, stretching from Dhaulagiri to Annapurna South and Machhapuchhre. Well-graded stone stairways and frequent teahouses make it suitable for first-time trekkers, families with older children, and anyone short on time who still wants an authentic Himalayan sunrise.",
    highlights: [
      "360° sunrise panorama from Poon Hill over Annapurna & Dhaulagiri",
      "Spectacular rhododendron forest, Nepal's national flower (best in March–April)",
      "Gurung and Magar hill villages",
      "Well-maintained trails suitable for beginners and families",
      "Short enough for a long weekend from Kathmandu",
    ],
    permits: ["Annapurna Conservation Area Permit (ACAP)", "TIMS Card"],
    itinerary: [
      { day: "Day 1", title: "Drive to Nayapul, trek to Tikhedhunga", detail: "Drive from Pokhara to Nayapul and trek to Tikhedhunga (1,540 m)." },
      { day: "Day 2", title: "Trek to Ghorepani", detail: "Climb through rhododendron forest to Ghorepani (2,860 m)." },
      { day: "Day 3", title: "Poon Hill sunrise, trek to Tadapani", detail: "Pre-dawn hike to Poon Hill, then descend and continue to Tadapani." },
      { day: "Day 4", title: "Trek to Ghandruk", detail: "Descend to the large Gurung village of Ghandruk with Annapurna and Fishtail views." },
      { day: "Day 5", title: "Trek to Nayapul, drive to Pokhara", detail: "Final descent to Nayapul and drive back to Pokhara." },
    ],
    included: ["Pokhara–Nayapul–Pokhara transport", "Licensed trekking guide", "Porter service (optional)", "Teahouse accommodation", "All permits"],
    excluded: ["Kathmandu–Pokhara transport", "Meals outside the trek", "Travel insurance", "Tips"],
    faqs: [
      { q: "Is Poon Hill Trek suitable for children?", a: "Yes — it is one of the few Himalayan treks we comfortably recommend for families with children aged 8 and up, given the moderate daily walking hours and low maximum altitude." },
    ],
  },
  {
    slug: "poon-hill-annapurna-base-camp-trek",
    name: "Poon Hill & Annapurna Base Camp Trek",
    region: "Annapurna Region",
    regionSlug: "annapurna",
    regionLabel: "Annapurna Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "Two of Annapurna's best viewpoints in one trip",
    heroImage: "/images/treks/annapurna-base-camp.jpg",
    gallery: ["/images/treks/annapurna-base-camp.jpg"],
    duration: "11 Days",
    durationDays: 11,
    maxAltitude: "4,130 m / 13,549 ft (Annapurna Base Camp)",
    difficulty: "Moderate",
    bestSeason: "March–May & September–December",
    groupSize: "2–12 (private trips available)",
    priceFrom: 850,
    restrictedArea: false,
    shortDescription:
      "Combine the sunrise panorama of Poon Hill with the dramatic high-altitude amphitheatre of Annapurna Base Camp in a single, well-paced 11-day trek.",
    overview:
      "For trekkers who want the full Annapurna experience, this combined itinerary links the gentle, forested trails and iconic sunrise of Ghorepani Poon Hill with the deeper, higher journey into the Annapurna Sanctuary to Annapurna Base Camp. The extra days built into this route give better acclimatization than a standalone ABC trek and let you experience a wider range of landscapes, from subtropical river valleys to high glacial moraine at the foot of Annapurna I.",
    highlights: [
      "Poon Hill sunrise over the Annapurna and Dhaulagiri ranges",
      "Annapurna Base Camp amphitheatre surrounded by 7,000–8,000 m peaks",
      "Natural hot springs at Jhinu Danda",
      "Gurung and Magar villages, rhododendron forest",
      "Better acclimatized pacing than the standalone ABC trek",
    ],
    permits: ["Annapurna Conservation Area Permit (ACAP)", "TIMS Card"],
    itinerary: [
      { day: "Day 1", title: "Drive to Nayapul, trek to Tikhedhunga", detail: "Drive from Pokhara to the trailhead and trek to Tikhedhunga (1,540 m)." },
      { day: "Day 2", title: "Trek to Ghorepani", detail: "Climb through rhododendron forest to Ghorepani (2,860 m)." },
      { day: "Day 3", title: "Poon Hill sunrise, trek to Tadapani", detail: "Sunrise hike to Poon Hill, then continue to Tadapani." },
      { day: "Day 4", title: "Trek to Chhomrong", detail: "Descend and climb to Chhomrong (2,170 m), gateway to the Sanctuary." },
      { day: "Day 5", title: "Trek to Bamboo/Dovan", detail: "Descend into the Modi Khola gorge toward Bamboo or Dovan." },
      { day: "Day 6", title: "Trek to Deurali", detail: "Continue climbing through forest and avalanche zones to Deurali (3,230 m)." },
      { day: "Day 7", title: "Trek to Annapurna Base Camp", detail: "Pass Machhapuchhre Base Camp to reach Annapurna Base Camp (4,130 m)." },
      { day: "Day 8", title: "Descend to Bamboo", detail: "Long descent back down the gorge." },
      { day: "Day 9", title: "Trek to Jhinu Danda", detail: "Continue descending to Jhinu Danda; relax in the natural hot springs." },
      { day: "Day 10", title: "Trek to Nayapul, drive to Pokhara", detail: "Final descent to Nayapul and drive back to Pokhara." },
      { day: "Day 11", title: "Contingency / Pokhara leisure day", detail: "Buffer day for weather delays, or free time in Pokhara." },
    ],
    included: ["Pokhara–Nayapul–Pokhara transport", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits"],
    excluded: ["Kathmandu–Pokhara transport", "Meals outside the trek", "Travel insurance", "Tips"],
    faqs: [
      { q: "Why combine Poon Hill with Annapurna Base Camp instead of doing ABC alone?", a: "The combined route adds gentler early days that help acclimatization, and gives you two distinct panoramas — Poon Hill's wide sunrise view and ABC's close-up amphitheatre — for only a couple of extra days on the trail." },
    ],
  },
  {
    slug: "annapurna-circuit-trek",
    name: "Annapurna Circuit Trek",
    region: "Annapurna Region",
    regionSlug: "annapurna",
    regionLabel: "Annapurna Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "Nepal's classic trans-Himalayan crossing",
    heroImage: "/images/treks/annapurna-base-camp.jpg",
    gallery: ["/images/treks/annapurna-base-camp.jpg"],
    duration: "14 Days",
    durationDays: 14,
    maxAltitude: "5,416 m / 17,769 ft (Thorong La Pass)",
    difficulty: "Challenging",
    bestSeason: "March–May & September–November",
    groupSize: "2–12 (private trips available)",
    priceFrom: 1050,
    restrictedArea: false,
    shortDescription:
      "A classic circuit around the Annapurna massif crossing Thorong La Pass (5,416 m), passing through subtropical valleys, high desert plateaus and the sacred temple of Muktinath.",
    overview:
      "The Annapurna Circuit is one of the world's great long-distance treks, circling the entire Annapurna massif and crossing the high Thorong La Pass (5,416 m) from the lush Marsyangdi valley into the arid, Tibetan-influenced Kali Gandaki valley. Over 14 days the landscape transforms dramatically — from rice terraces and waterfalls to pine forest, alpine yak pasture, and finally the high-desert plateau around Manang and Muktinath. Road construction has shortened some of the lower sections in recent years, and our itinerary uses jeep transfers where the trail has been affected by roads, keeping the walking on the most scenic, trail-only sections.",
    highlights: [
      "Crossing Thorong La Pass (5,416 m), one of the highest trekking passes in the world",
      "Muktinath Temple, sacred to both Hindus and Buddhists",
      "Manang, a high-altitude Tibetan-influenced trading town",
      "Dramatic transition from subtropical forest to high desert",
      "Views of Annapurna II, III, IV, Gangapurna and Dhaulagiri",
    ],
    permits: ["Annapurna Conservation Area Permit (ACAP)", "TIMS Card"],
    itinerary: [
      { day: "Day 1", title: "Drive Kathmandu to Chame", detail: "Drive via Besisahar to Chame (2,710 m), starting the circuit above the roadhead." },
      { day: "Day 2", title: "Trek to Upper Pisang", detail: "Walk beside the Marsyangdi river to Upper Pisang (3,300 m)." },
      { day: "Day 3", title: "Trek to Manang", detail: "Follow the scenic high route via Ghyaru and Ngawal to Manang (3,540 m)." },
      { day: "Day 4", title: "Acclimatization in Manang", detail: "Day hike to Gangapurna Lake or the Praken Gompa viewpoint." },
      { day: "Day 5", title: "Trek to Yak Kharka", detail: "Gentle climb to the yak-grazing settlement of Yak Kharka (4,050 m)." },
      { day: "Day 6", title: "Trek to Thorong Phedi/High Camp", detail: "Short but steep climb to Thorong Phedi or High Camp (4,600–4,925 m) to prepare for the pass." },
      { day: "Day 7", title: "Cross Thorong La to Muktinath", detail: "Pre-dawn crossing of Thorong La Pass (5,416 m), descending to Muktinath (3,760 m)." },
      { day: "Day 8", title: "Drive/trek to Marpha", detail: "Visit Muktinath Temple, then continue to the apple-orchard village of Marpha." },
      { day: "Day 9", title: "Trek to Kalopani", detail: "Walk through the deep Kali Gandaki gorge, the world's deepest, to Kalopani." },
      { day: "Day 10", title: "Trek to Tatopani", detail: "Descend to Tatopani, known for its natural hot springs." },
      { day: "Day 11", title: "Trek to Ghorepani", detail: "Climb through forest toward Ghorepani (2,860 m)." },
      { day: "Day 12", title: "Poon Hill sunrise, trek to Tikhedhunga", detail: "Sunrise at Poon Hill, then descend toward Tikhedhunga." },
      { day: "Day 13", title: "Trek to Nayapul, drive to Pokhara", detail: "Final descent to Nayapul and drive to Pokhara." },
      { day: "Day 14", title: "Drive/fly to Kathmandu", detail: "Return to Kathmandu by tourist bus or flight." },
    ],
    included: ["Kathmandu–Chame ground transport", "Pokhara–Kathmandu return transport", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits"],
    excluded: ["Meals in Kathmandu/Pokhara", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "How difficult is crossing Thorong La Pass?", a: "Thorong La is challenging mainly because of altitude and an early pre-dawn start, not technical climbing — no ropes or crampons are needed in normal conditions. Proper acclimatization days in Manang, which we build into every itinerary, are essential." },
    ],
  },
  {
    slug: "manaslu-circuit-trek",
    name: "Manaslu Circuit Trek",
    region: "Manaslu Region",
    regionSlug: "manaslu",
    regionLabel: "Manaslu Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "A wilder, quieter circuit beneath the eighth-highest peak",
    heroImage: "/images/treks/manaslu-circuit.jpg",
    gallery: ["/images/treks/manaslu-circuit.jpg"],
    duration: "14 Days",
    durationDays: 14,
    maxAltitude: "5,106 m / 16,752 ft (Larkya La Pass)",
    difficulty: "Challenging",
    bestSeason: "March–May & September–November",
    groupSize: "Minimum 2 trekkers (restricted area regulation)",
    priceFrom: 1450,
    restrictedArea: true,
    shortDescription:
      "Circle Manaslu (8,163 m), the world's eighth-highest mountain, on a restricted-area trek through remote Gurung and Tibetan-influenced villages, crossing the dramatic Larkya La Pass.",
    overview:
      "The Manaslu Circuit is often described as what the Annapurna Circuit was before it was developed — a genuinely remote trail that circles Manaslu (8,163 m) through the Budhi Gandaki gorge, passing lower Gurung villages before climbing into the Tibetan-influenced upper valley near Samagaon and Samdo. As a restricted area, it requires a licensed guide and a minimum of two trekkers, which keeps the trail far less crowded than Everest or Annapurna. The trek's high point, Larkya La Pass (5,106 m), delivers views of Manaslu, Himlung Himal and Annapurna II across a dramatic glacial landscape.",
    highlights: [
      "Crossing the remote Larkya La Pass (5,106 m)",
      "Close-up views of Manaslu (8,163 m), the world's 8th-highest peak",
      "Tibetan-influenced villages of Samagaon and Samdo",
      "One of Nepal's quietest restricted-area treks",
      "Deep Budhi Gandaki river gorge and suspension bridges",
    ],
    permits: [
      "Manaslu Restricted Area Permit (RAP)",
      "Manaslu Conservation Area Permit (MCAP)",
      "Annapurna Conservation Area Permit (ACAP)",
    ],
    itinerary: [
      { day: "Day 1", title: "Drive Kathmandu to Machha Khola", detail: "Long scenic drive to the trailhead at Machha Khola (930 m)." },
      { day: "Day 2", title: "Trek to Jagat", detail: "Follow the Budhi Gandaki gorge to Jagat (1,340 m), entrance to the restricted area." },
      { day: "Day 3", title: "Trek to Deng", detail: "Continue upriver through forest and villages to Deng (1,860 m)." },
      { day: "Day 4", title: "Trek to Namrung", detail: "Climb steadily to Namrung (2,630 m), first views of Manaslu appear." },
      { day: "Day 5", title: "Trek to Samagaon", detail: "Enter the Tibetan-influenced upper valley to Samagaon (3,530 m)." },
      { day: "Day 6", title: "Acclimatization in Samagaon", detail: "Day hike to Manaslu Base Camp or Birendra Lake." },
      { day: "Day 7", title: "Trek to Samdo", detail: "Short walk to the high village of Samdo (3,875 m), near the Tibet border." },
      { day: "Day 8", title: "Acclimatization/trek to Dharamshala", detail: "Move up to Dharamshala/Larke Phedi (4,460 m) to prepare for the pass." },
      { day: "Day 9", title: "Cross Larkya La to Bimthang", detail: "Cross Larkya La Pass (5,106 m), descending to Bimthang (3,720 m)." },
      { day: "Day 10", title: "Trek to Tilije", detail: "Descend through forest into the Marsyangdi valley to Tilije." },
      { day: "Day 11", title: "Trek to Dharapani/Jagat", detail: "Continue down-valley, joining the lower Annapurna Circuit trail." },
      { day: "Day 12", title: "Drive to Besisahar, then Kathmandu", detail: "Jeep transfer out of the mountains and drive back toward Kathmandu." },
      { day: "Day 13", title: "Kathmandu leisure day", detail: "Buffer day for road delays, or sightseeing in Kathmandu." },
      { day: "Day 14", title: "Departure", detail: "Transfer to the airport for your onward flight." },
    ],
    included: ["All ground transport", "Licensed trekking guide", "Porter service", "Teahouse/basic lodge accommodation", "All permits (RAP, MCAP, ACAP)"],
    excluded: ["Meals in Kathmandu", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "Why does the Manaslu Circuit need a special permit?", a: "Manaslu is a restricted trekking area under Nepali regulation, meaning independent trekking is not allowed — you must trek with a registered agency, a licensed guide, and a minimum of two trekkers, which we arrange as part of every booking." },
    ],
  },
  {
    slug: "upper-mustang-trek",
    name: "Upper Mustang Trek",
    region: "Mustang Region",
    regionSlug: "mustang",
    regionLabel: "Mustang Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "The last forbidden kingdom of the Himalaya",
    heroImage: "/images/gallery/pikey-peak.jpg",
    gallery: ["/images/gallery/pikey-peak.jpg"],
    duration: "12 Days",
    durationDays: 12,
    maxAltitude: "3,840 m / 12,598 ft (Lo Manthang)",
    difficulty: "Moderate",
    bestSeason: "June–September (rain-shadow, trekkable in monsoon) & March–November",
    groupSize: "Minimum 2 trekkers (restricted area regulation)",
    priceFrom: 1650,
    restrictedArea: true,
    shortDescription:
      "Journey into the walled city of Lo Manthang across a wind-carved, high-desert landscape that preserves centuries-old Tibetan Buddhist culture, largely untouched by modern development.",
    overview:
      "Upper Mustang was closed to outsiders until 1992 and still requires a special restricted-area permit, which limits visitor numbers and keeps its Tibetan Buddhist culture remarkably intact. The trek climbs from Kagbeni into a rain-shadow desert of ochre cliffs, wind-eroded canyons and cave dwellings to Lo Manthang, the walled former capital of the Mustang kingdom, still home to a functioning royal palace and centuries-old monasteries. Because Mustang sits in the rain shadow of the Annapurna and Dhaulagiri ranges, it is one of the few Himalayan treks that remains excellent even during the summer monsoon, when most of Nepal is under cloud.",
    highlights: [
      "Lo Manthang, the walled former capital of the Mustang kingdom",
      "Trekkable during the monsoon season, unlike most of Nepal",
      "Centuries-old monasteries, chortens and cave dwellings",
      "Tibetan Buddhist culture largely unchanged for generations",
      "Dramatic desert canyon scenery unlike anywhere else in Nepal",
    ],
    permits: ["Upper Mustang Restricted Area Permit (special permit)", "Annapurna Conservation Area Permit (ACAP)"],
    itinerary: [
      { day: "Day 1", title: "Fly Kathmandu–Pokhara–Jomsom, trek to Kagbeni", detail: "Fly to Jomsom (2,720 m) via Pokhara, then trek to Kagbeni, gateway to Upper Mustang." },
      { day: "Day 2", title: "Trek to Chele", detail: "Enter the restricted area and climb into the high-desert landscape toward Chele." },
      { day: "Day 3", title: "Trek to Geling/Ghami", detail: "Cross windswept plateaus and passes to Geling or Ghami." },
      { day: "Day 4", title: "Trek to Charang", detail: "Visit Ghami's long mani wall and continue to Charang, with its red monastery and old fort." },
      { day: "Day 5", title: "Trek to Lo Manthang", detail: "Reach the walled city of Lo Manthang (3,840 m)." },
      { day: "Day 6", title: "Explore Lo Manthang", detail: "Full day visiting the royal palace, Thubchen and Jampa monasteries, and surrounding caves." },
      { day: "Day 7", title: "Day trip to Chhoser caves", detail: "Optional excursion to the ancient Sky Caves of Chhoser." },
      { day: "Day 8", title: "Trek to Ghami (return route)", detail: "Begin the return journey via a variant route through Dhakmar's red cliffs." },
      { day: "Day 9", title: "Trek to Chele", detail: "Continue the descent back toward Kagbeni." },
      { day: "Day 10", title: "Trek to Jomsom", detail: "Final trekking day back to Jomsom via Kagbeni." },
      { day: "Day 11", title: "Fly to Pokhara", detail: "Morning flight from Jomsom to Pokhara; free time by Phewa Lake." },
      { day: "Day 12", title: "Fly/drive to Kathmandu", detail: "Return to Kathmandu and transfer for departure." },
    ],
    included: ["All internal flights (KTM–PKR–JOM–PKR–KTM)", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "Restricted area permit & ACAP"],
    excluded: ["Meals in Kathmandu/Pokhara", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "Why is the Upper Mustang permit so expensive?", a: "The Nepali government caps visitor numbers to Upper Mustang to protect its fragile culture and environment, funded through a special restricted-area fee — currently around USD 500 for the first 10 days per person, which we include in your package price." },
      { q: "Can Upper Mustang be trekked during monsoon?", a: "Yes — Mustang sits in a rain shadow, so June to September, when most of Nepal is cloudy and wet, is actually one of the best windows to trek here." },
    ],
  },
  {
    slug: "upper-dolpo-trek",
    name: "Upper Dolpo Trek",
    region: "Dolpo Region",
    regionSlug: "dolpo",
    regionLabel: "Dolpo Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "Nepal's remotest trans-Himalayan wilderness",
    heroImage: "/images/treks/upper-dolpo.jpg",
    gallery: ["/images/treks/upper-dolpo.jpg"],
    duration: "20 Days",
    durationDays: 20,
    maxAltitude: "5,190 m / 17,027 ft (Numa La Pass)",
    difficulty: "Strenuous",
    bestSeason: "June–September (rain-shadow trekking season)",
    groupSize: "Minimum 2 trekkers (restricted area regulation)",
    priceFrom: 2200,
    restrictedArea: true,
    shortDescription:
      "One of the most remote treks on earth — a wilderness crossing to Shey Gompa and turquoise Phoksundo Lake, through Bon Po villages barely touched by the outside world.",
    overview:
      "Upper Dolpo is the setting of Peter Matthiessen's 'The Snow Leopard' and Eric Valli's film 'Caravan,' and remains one of the most remote and least visited trekking regions in the Himalaya. The trek crosses multiple 5,000 m passes through a stark trans-Himalayan landscape into the Shey Phoksundo National Park, visiting Shey Gompa — a sacred Bon Po monastery beneath the Crystal Mountain — and the impossibly turquoise Phoksundo Lake. This is a genuine wilderness expedition requiring full camping support, a minimum group of two, and a real appetite for remoteness; there are no teahouses in Upper Dolpo, and villages are days apart.",
    highlights: [
      "Shey Gompa, a sacred Bon Po monastery beneath the Crystal Mountain",
      "Phoksundo Lake, one of the deepest and most vividly turquoise lakes in Nepal",
      "Crossing multiple high passes including Numa La and Baga La",
      "Snow leopard habitat and genuine wilderness camping",
      "Bon Po culture found almost nowhere else in Nepal",
    ],
    permits: [
      "Upper Dolpo Restricted Area Permit (special permit)",
      "Shey Phoksundo National Park Entry Permit",
    ],
    itinerary: [
      { day: "Day 1–2", title: "Kathmandu to Juphal via Nepalgunj", detail: "Fly Kathmandu–Nepalgunj–Juphal, then trek to Dunai (2,140 m), Dolpo's district headquarters." },
      { day: "Day 3–4", title: "Trek to Phoksundo Lake", detail: "Follow the Suli Gad river through forest to the shores of turquoise Phoksundo Lake (3,612 m)." },
      { day: "Day 5", title: "Rest and exploration day", detail: "Explore Ringmo village and the Phoksundo waterfall, Nepal's highest." },
      { day: "Day 6–8", title: "Trek toward Shey Gompa", detail: "Cross remote high terrain via Kang La Pass (5,360 m) to reach Shey Gompa." },
      { day: "Day 9", title: "Explore Shey Gompa", detail: "Rest day visiting the monastery beneath the sacred Crystal Mountain." },
      { day: "Day 10–13", title: "Cross Numa La and Baga La passes", detail: "Two of the trek's high passes (around 5,190 m and 5,070 m) lead into the Tarap valley." },
      { day: "Day 14–16", title: "Trek through Tarap Valley", detail: "Walk through the wide, Tibetan-influenced Tarap valley and its Bon Po villages." },
      { day: "Day 17–19", title: "Trek back to Juphal", detail: "Descend via Tarakot back to Dunai and on to Juphal." },
      { day: "Day 20", title: "Fly to Nepalgunj and Kathmandu", detail: "Return flights back to Kathmandu." },
    ],
    included: ["All internal flights", "Licensed trekking guide & Dolpo-region camping crew", "Full camping equipment and cook staff", "All meals during the trek", "Restricted area & national park permits"],
    excluded: ["Meals in Kathmandu", "Travel insurance (incl. helicopter evacuation)", "Personal gear", "Tips"],
    faqs: [
      { q: "Do I need camping gear for Upper Dolpo?", a: "No — we provide full camping equipment, a cook team and all meals as part of the package, since teahouses do not exist along most of this route." },
      { q: "Why is Upper Dolpo trekked in summer instead of spring/autumn?", a: "Like Upper Mustang, Dolpo lies in a rain shadow, so June–September avoids both the winter snow that closes its high passes and the monsoon rain that affects the rest of Nepal." },
    ],
  },
  {
    slug: "lower-dolpo-trek",
    name: "Lower Dolpo Trek",
    region: "Dolpo Region",
    regionSlug: "dolpo",
    regionLabel: "Dolpo Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "Turquoise lakes and Bon Po villages, fewer permits required",
    heroImage: "/images/treks/upper-dolpo.jpg",
    gallery: ["/images/treks/upper-dolpo.jpg"],
    duration: "14 Days",
    durationDays: 14,
    maxAltitude: "5,190 m / 17,027 ft (Numa La Pass)",
    difficulty: "Challenging",
    bestSeason: "June–September & March–May",
    groupSize: "2–8 (restricted area regulation)",
    priceFrom: 1750,
    restrictedArea: true,
    shortDescription:
      "A shorter, slightly more accessible route into the Dolpo wilderness, centred on the turquoise Phoksundo Lake and the high Numa La and Baga La passes, without pushing as far as Shey Gompa.",
    overview:
      "Lower Dolpo shares the same starting point and turquoise-lake highlight as its Upper Dolpo neighbour but wraps up in roughly two-thirds the time, making the region's raw, little-visited landscape reachable without a three-week commitment. The route follows the Suli Gad river to Phoksundo Lake, then climbs over the Numa La and Baga La passes into the wide Tarap valley, home to Bon Po villages that predate Tibetan Buddhism in the region. It still requires a special permit and camping support, but sees a fraction of the trekkers found on Everest or Annapurna trails.",
    highlights: [
      "Phoksundo Lake and Nepal's highest waterfall at Ringmo",
      "Crossing Numa La and Baga La passes",
      "Tarap Valley's ancient Bon Po villages",
      "A shorter, more achievable alternative to Upper Dolpo",
      "Some of the lowest trekker traffic of any route in Nepal",
    ],
    permits: [
      "Dolpo Restricted Area Permit",
      "Shey Phoksundo National Park Entry Permit",
    ],
    itinerary: [
      { day: "Day 1–2", title: "Kathmandu to Juphal via Nepalgunj", detail: "Fly Kathmandu–Nepalgunj–Juphal, then trek to Dunai (2,140 m)." },
      { day: "Day 3–4", title: "Trek to Phoksundo Lake", detail: "Follow the Suli Gad river to the shores of Phoksundo Lake (3,612 m)." },
      { day: "Day 5", title: "Rest and exploration day", detail: "Explore Ringmo village and the Phoksundo waterfall." },
      { day: "Day 6–8", title: "Cross Numa La and Baga La passes", detail: "Trek over both high passes (around 5,190 m and 5,070 m) into the Tarap valley." },
      { day: "Day 9–10", title: "Explore Tarap Valley", detail: "Visit Bon Po villages and monasteries in the wide upper valley." },
      { day: "Day 11–13", title: "Trek back to Juphal", detail: "Descend via Tarakot and Dunai back to Juphal." },
      { day: "Day 14", title: "Fly to Nepalgunj and Kathmandu", detail: "Return flights back to Kathmandu." },
    ],
    included: ["All internal flights", "Licensed trekking guide & camping crew", "Full camping equipment and all trek meals", "Restricted area & national park permits"],
    excluded: ["Meals in Kathmandu", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "What is the difference between Upper and Lower Dolpo treks?", a: "Lower Dolpo covers Phoksundo Lake and the Tarap valley in about 14 days, while Upper Dolpo continues further to the remote Shey Gompa monastery over a full three-week itinerary. Both require the same style of camping support." },
    ],
  },
  {
    slug: "mardi-himal-trek",
    name: "Mardi Himal Trek",
    region: "Annapurna Region",
    regionSlug: "annapurna",
    regionLabel: "Annapurna Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "A quiet ridge trail eye-to-eye with Fishtail",
    heroImage: "/images/treks/mardi-himal.jpg",
    gallery: ["/images/treks/mardi-himal.jpg"],
    duration: "6 Days",
    durationDays: 6,
    maxAltitude: "4,500 m / 14,764 ft (Mardi Himal Base Camp)",
    difficulty: "Moderate",
    bestSeason: "March–May & September–December",
    groupSize: "2–12 (private trips available)",
    priceFrom: 500,
    restrictedArea: false,
    shortDescription:
      "A relatively new, less-crowded ridge trek out of Pokhara leading to close-up views of Machhapuchhre (Fishtail) and the Annapurna range from a dramatic knife-edge trail.",
    overview:
      "Opened to trekkers only in the last two decades, the Mardi Himal Trek climbs a narrow forested ridge directly toward Machhapuchhre (Fishtail, 6,993 m), a peak that remains unclimbed and considered sacred. Because it diverges from the busier Annapurna Base Camp trail, Mardi Himal sees far fewer trekkers while delivering some of the closest mountain views of any moderate trek near Pokhara, culminating at a high viewpoint and base camp at 4,500 m with Annapurna South and Hiunchuli towering directly overhead.",
    highlights: [
      "Extreme close-up views of Machhapuchhre (Fishtail)",
      "One of the least crowded trails in the Annapurna region",
      "Rhododendron forest giving way to dramatic alpine ridge walking",
      "Short enough for a one-week trip from Pokhara",
      "High viewpoint at 4,500 m without technical climbing",
    ],
    permits: ["Annapurna Conservation Area Permit (ACAP)", "TIMS Card"],
    itinerary: [
      { day: "Day 1", title: "Drive Pokhara to Kande, trek to Pothana", detail: "Short drive to the trailhead at Kande, trek to Pothana (1,890 m)." },
      { day: "Day 2", title: "Trek to Forest Camp/Low Camp", detail: "Climb through rhododendron forest onto the Mardi ridge to Low Camp (2,970 m)." },
      { day: "Day 3", title: "Trek to High Camp", detail: "Continue along the narrowing ridge to High Camp (3,580 m), with Machhapuchhre now dominating the skyline." },
      { day: "Day 4", title: "Trek to Mardi Himal Base Camp and back to Low Camp", detail: "Early climb to the viewpoint/base camp (4,500 m) for close-up mountain views, then descend to Low Camp." },
      { day: "Day 5", title: "Trek to Siding village", detail: "Descend off the ridge into the traditional Gurung village of Siding." },
      { day: "Day 6", title: "Drive back to Pokhara", detail: "Short drive from Siding back to Pokhara." },
    ],
    included: ["Pokhara–Kande and Siding–Pokhara transport", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits"],
    excluded: ["Kathmandu–Pokhara transport", "Meals outside the trek", "Travel insurance", "Tips"],
    faqs: [
      { q: "Is Mardi Himal less crowded than Annapurna Base Camp?", a: "Yes — Mardi Himal branches off the main ABC trail onto its own ridge, so even in peak season it sees noticeably fewer trekkers while offering equally dramatic close-up mountain views." },
    ],
  },
  {
    slug: "gokyo-valley-trek",
    name: "Gokyo Valley Trek",
    region: "Khumbu / Everest Region",
    regionSlug: "everest",
    regionLabel: "Everest Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "Turquoise lakes and the best summit view in the Khumbu",
    heroImage: "/images/treks/everest-base-camp-2.jpg",
    gallery: ["/images/treks/everest-base-camp-2.jpg"],
    duration: "14 Days",
    durationDays: 14,
    maxAltitude: "5,357 m / 17,575 ft (Gokyo Ri)",
    difficulty: "Challenging",
    bestSeason: "March–May & September–November",
    groupSize: "2–12 (private trips available)",
    priceFrom: 1450,
    restrictedArea: false,
    shortDescription:
      "A quieter alternative to Everest Base Camp, following the Dudh Koshi valley up to the turquoise Gokyo Lakes and a sunrise climb of Gokyo Ri for arguably the best mountain panorama in the Khumbu.",
    overview:
      "The Gokyo Valley Trek follows a different branch of the Khumbu than the classic Everest Base Camp trail, climbing beside the Ngozumpa Glacier — Nepal's largest — to the emerald Gokyo Lakes at 4,700–5,000 m. From the summit of Gokyo Ri (5,357 m) you get an unobstructed view of four of the world's six highest peaks — Everest, Lhotse, Makalu and Cho Oyu — from a single point, widely regarded as the finest panorama in the entire Khumbu region and with far fewer trekkers than the EBC trail.",
    highlights: [
      "Four 8,000ers visible from a single viewpoint at Gokyo Ri",
      "The turquoise Gokyo Lakes beside the Ngozumpa Glacier",
      "Significantly quieter trails than the classic EBC route",
      "Optional side trip across the glacier to Cho La Pass toward EBC",
      "Namche Bazaar and Sherpa villages en route",
    ],
    permits: ["Sagarmatha National Park Entry Permit", "Khumbu Pasang Lhamu Rural Municipality Entry Permit"],
    itinerary: [
      { day: "Day 1", title: "Arrive in Kathmandu", detail: "Airport pickup, welcome briefing and gear check." },
      { day: "Day 2", title: "Fly to Lukla, trek to Phakding", detail: "Scenic flight to Lukla (2,860 m), short trek to Phakding." },
      { day: "Day 3", title: "Trek to Namche Bazaar", detail: "Climb into Sagarmatha National Park to Namche Bazaar (3,440 m)." },
      { day: "Day 4", title: "Acclimatization in Namche", detail: "Day hike to the Everest View Hotel for first mountain views." },
      { day: "Day 5", title: "Trek to Dole", detail: "Branch off the main EBC trail up the Dudh Koshi valley to Dole (4,200 m)." },
      { day: "Day 6", title: "Trek to Machhermo", detail: "Continue up-valley to Machhermo (4,470 m)." },
      { day: "Day 7", title: "Trek to Gokyo", detail: "Follow the Ngozumpa Glacier to the Gokyo Lakes (4,790 m)." },
      { day: "Day 8", title: "Gokyo Ri sunrise", detail: "Pre-dawn climb to Gokyo Ri (5,357 m) for the four-8,000er panorama." },
      { day: "Day 9", title: "Trek to Dole", detail: "Begin the descent back down the valley." },
      { day: "Day 10", title: "Trek to Namche Bazaar", detail: "Continue the descent to Namche." },
      { day: "Day 11", title: "Trek to Lukla", detail: "Final descent to Lukla." },
      { day: "Day 12", title: "Fly to Kathmandu", detail: "Morning flight back to Kathmandu." },
      { day: "Day 13", title: "Kathmandu leisure day", detail: "Buffer day for flight delays, or sightseeing." },
      { day: "Day 14", title: "Departure", detail: "Transfer to the airport for your onward flight." },
    ],
    included: ["Airport transfers", "Kathmandu–Lukla–Kathmandu flights", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits"],
    excluded: ["Nepal visa fee", "Travel insurance", "Meals in Kathmandu", "Personal gear", "Tips"],
    faqs: [
      { q: "Is Gokyo Valley better than Everest Base Camp?", a: "They're different experiences — EBC gets you to the foot of Everest itself, while Gokyo Ri gives you a wider panorama including Everest from a distance, with quieter trails. Some guests combine both via the Cho La Pass." },
    ],
  },
  {
    slug: "everest-three-passes-trek",
    name: "Everest Three Passes Trek",
    region: "Khumbu / Everest Region",
    regionSlug: "everest",
    regionLabel: "Everest Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "The Khumbu's ultimate challenge — three high passes, one trek",
    heroImage: "/images/treks/everest-base-camp-3.jpg",
    gallery: ["/images/treks/everest-base-camp-3.jpg"],
    duration: "21 Days",
    durationDays: 21,
    maxAltitude: "5,545 m / 18,192 ft (Kala Patthar)",
    difficulty: "Strenuous",
    bestSeason: "March–May & September–November",
    groupSize: "2–10 (private trips available)",
    priceFrom: 2200,
    restrictedArea: false,
    shortDescription:
      "The most complete way to see the Khumbu: Everest Base Camp, the Gokyo Lakes and all three of the region's high passes — Kongma La, Cho La and Renjo La — in one demanding loop.",
    overview:
      "The Three Passes Trek links together everything the Khumbu has to offer by crossing all three of the region's high passes — Kongma La (5,535 m), Cho La (5,420 m) and Renjo La (5,360 m) — while also visiting both Everest Base Camp and the Gokyo Lakes. It is the most physically demanding standard itinerary in the region, recommended for trekkers with prior high-altitude experience, and rewards the effort with a genuinely complete circuit of the Khumbu's best viewpoints without repeating trail.",
    highlights: [
      "All three of the Khumbu's high passes in a single trek",
      "Both Everest Base Camp and the Gokyo Lakes on one itinerary",
      "Kala Patthar sunrise and Gokyo Ri panoramas",
      "Genuinely remote, quiet trail sections between the passes",
      "The complete Khumbu experience for experienced trekkers",
    ],
    permits: ["Sagarmatha National Park Entry Permit", "Khumbu Pasang Lhamu Rural Municipality Entry Permit"],
    itinerary: [
      { day: "Day 1", title: "Arrive in Kathmandu", detail: "Airport pickup and trek briefing." },
      { day: "Day 2", title: "Fly to Lukla, trek to Phakding", detail: "Flight to Lukla, short trek to Phakding." },
      { day: "Day 3", title: "Trek to Namche Bazaar", detail: "Climb to Namche Bazaar (3,440 m)." },
      { day: "Day 4", title: "Acclimatization in Namche", detail: "Day hike to Khumjung village." },
      { day: "Day 5", title: "Trek to Tengboche", detail: "Walk to Tengboche Monastery (3,860 m)." },
      { day: "Day 6", title: "Trek to Dingboche", detail: "Continue to Dingboche (4,410 m)." },
      { day: "Day 7", title: "Acclimatization in Dingboche", detail: "Hike to Nangkartshang viewpoint." },
      { day: "Day 8", title: "Trek to Chhukung", detail: "Short walk to Chhukung (4,730 m), staging point for Kongma La." },
      { day: "Day 9", title: "Cross Kongma La to Lobuche", detail: "Cross the first pass, Kongma La (5,535 m), to Lobuche." },
      { day: "Day 10", title: "Trek to Gorak Shep & Everest Base Camp", detail: "Reach Gorak Shep, then Everest Base Camp (5,364 m)." },
      { day: "Day 11", title: "Kala Patthar sunrise, trek to Dzongla", detail: "Sunrise at Kala Patthar (5,545 m), then on to Dzongla." },
      { day: "Day 12", title: "Cross Cho La to Thagnak", detail: "Cross the second pass, Cho La (5,420 m), to Thagnak." },
      { day: "Day 13", title: "Trek to Gokyo", detail: "Short walk to the Gokyo Lakes (4,790 m)." },
      { day: "Day 14", title: "Gokyo Ri sunrise", detail: "Climb Gokyo Ri (5,357 m) for the four-8,000er view." },
      { day: "Day 15", title: "Cross Renjo La to Lungden", detail: "Cross the third pass, Renjo La (5,360 m)." },
      { day: "Day 16", title: "Trek to Namche Bazaar", detail: "Descend back to Namche Bazaar." },
      { day: "Day 17", title: "Trek to Lukla", detail: "Final descent to Lukla." },
      { day: "Day 18", title: "Fly to Kathmandu", detail: "Morning flight back to Kathmandu." },
      { day: "Day 19", title: "Kathmandu buffer day", detail: "Contingency day for weather delays." },
      { day: "Day 20", title: "Kathmandu leisure day", detail: "Free day for sightseeing or rest." },
      { day: "Day 21", title: "Departure", detail: "Transfer to the airport for your onward flight." },
    ],
    included: ["Airport transfers", "Kathmandu–Lukla–Kathmandu flights", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits"],
    excluded: ["Nepal visa fee", "Travel insurance (incl. helicopter evacuation)", "Meals in Kathmandu", "Personal gear", "Tips"],
    faqs: [
      { q: "Do I need prior trekking experience for the Three Passes Trek?", a: "Yes — we recommend at least one prior high-altitude trek (such as EBC or Annapurna Circuit) before attempting this route, given the cumulative altitude gain and three consecutive high-pass crossings." },
    ],
  },
  {
    slug: "pikey-peak-trek",
    name: "Pikey Peak Trek",
    region: "Khumbu / Everest Region",
    regionSlug: "everest",
    regionLabel: "Everest Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "The Everest panorama without the crowds — or the altitude risk",
    heroImage: "/images/gallery/pikey-peak.jpg",
    gallery: ["/images/gallery/pikey-peak.jpg"],
    duration: "10 Days",
    durationDays: 10,
    maxAltitude: "4,065 m / 13,336 ft (Pikey Peak)",
    difficulty: "Moderate",
    bestSeason: "March–May & September–December",
    groupSize: "2–12 (private trips available)",
    priceFrom: 850,
    restrictedArea: false,
    shortDescription:
      "A short, uncrowded trek through Sherpa and Rai villages south of the Khumbu to Pikey Peak, once called by Sir Edmund Hillary the best sunrise viewpoint over Everest he had seen.",
    overview:
      "Pikey Peak sits south of the main Khumbu trekking trails, reached through forested hills and traditional Sherpa and Rai villages that see a fraction of the foot traffic of the EBC route. The reward at the top is a 360-degree panorama that takes in Everest, Lhotse, Makalu, Kanchenjunga and the Annapurna and Langtang ranges in a single sweep — without the altitude risk, Lukla flight dependency, or crowds of the classic Everest treks. It's an excellent choice for trekkers short on time or new to high-altitude walking.",
    highlights: [
      "A 360° Himalayan panorama including Everest, without flying into Lukla",
      "Quiet trails through traditional Sherpa and Rai villages",
      "Lower altitude and shorter duration than the classic EBC trek",
      "Rhododendron forest en route (spectacular in spring)",
      "A drive-in, drive-out trek — no dependency on mountain flights",
    ],
    permits: ["Gaurishankar Conservation Area Permit", "TIMS Card"],
    itinerary: [
      { day: "Day 1", title: "Drive Kathmandu to Jiri or Dhap", detail: "Scenic drive out of the Kathmandu Valley to the trailhead." },
      { day: "Day 2", title: "Trek to Bhulbhule", detail: "Begin walking through forested hill villages." },
      { day: "Day 3", title: "Trek to Panchakanya Pokhari", detail: "Continue climbing through Rai and Sherpa settlements." },
      { day: "Day 4", title: "Trek to Pikey Base Camp", detail: "Approach the base of Pikey Peak." },
      { day: "Day 5", title: "Pikey Peak sunrise, trek to Junbesi", detail: "Pre-dawn climb to Pikey Peak (4,065 m) for the panorama, then descend to Junbesi." },
      { day: "Day 6", title: "Trek to Ringmo", detail: "Visit Thubten Chholing Monastery en route to Ringmo." },
      { day: "Day 7", title: "Trek to Phaplu", detail: "Descend through apple-orchard villages to Phaplu." },
      { day: "Day 8", title: "Drive/fly to Kathmandu", detail: "Return to Kathmandu by road or short flight from Phaplu." },
      { day: "Day 9", title: "Kathmandu leisure day", detail: "Free day for sightseeing or rest." },
      { day: "Day 10", title: "Departure", detail: "Transfer to the airport for your onward flight." },
    ],
    included: ["Ground transport", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits"],
    excluded: ["Meals in Kathmandu", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "Is Pikey Peak a good alternative to Everest Base Camp?", a: "If your goal is mountain views rather than reaching EBC itself, yes — Pikey Peak gives a wider panorama including Everest in about a third of the time, at roughly a third of the altitude, and without needing the Lukla flight." },
    ],
  },
  {
    slug: "nar-phu-valley-trek",
    name: "Nar Phu Valley Trek",
    region: "Annapurna Region",
    regionSlug: "annapurna",
    regionLabel: "Annapurna Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "A hidden restricted valley on the edge of the Annapurna Circuit",
    heroImage: "/images/treks/annapurna-base-camp.jpg",
    gallery: ["/images/treks/annapurna-base-camp.jpg"],
    duration: "15 Days",
    durationDays: 15,
    maxAltitude: "5,320 m / 17,454 ft (Kang La Pass)",
    difficulty: "Challenging",
    bestSeason: "March–May & September–November",
    groupSize: "Minimum 2 trekkers (restricted area regulation)",
    priceFrom: 1950,
    restrictedArea: true,
    shortDescription:
      "A restricted-area side valley off the Annapurna Circuit, visiting the walled, Tibetan-influenced villages of Nar and Phu before crossing back over the Kang La Pass to Manang.",
    overview:
      "Tucked into a narrow gorge off the main Annapurna Circuit trail, Nar and Phu were only opened to trekkers in 2003 and remain one of the least-visited restricted areas in Nepal. The valley's two villages — walled, medieval-looking settlements of flat-roofed stone houses — preserve a Tibetan Buddhist culture largely unchanged for centuries. The trek combines naturally with the Annapurna Circuit, entering via the Nar Phu gorge below Koto and rejoining the main circuit at Manang via the Kang La Pass (5,320 m).",
    highlights: [
      "The walled villages of Nar and Phu, virtually unchanged for centuries",
      "One of Nepal's least-visited restricted trekking areas",
      "Dramatic narrow gorge approach unlike any other Annapurna trail",
      "Kang La Pass crossing back to the main Annapurna Circuit",
      "Ancient monasteries including Tashi Lhakhang Gompa",
    ],
    permits: ["Nar Phu Restricted Area Permit", "Annapurna Conservation Area Permit (ACAP)"],
    itinerary: [
      { day: "Day 1", title: "Drive Kathmandu to Koto", detail: "Long scenic drive via Besisahar into the Marsyangdi valley." },
      { day: "Day 2", title: "Trek to Meta", detail: "Enter the Nar Phu gorge, climbing steeply to Meta (3,560 m)." },
      { day: "Day 3", title: "Trek to Phu village", detail: "Continue up the narrowing gorge to the walled village of Phu (4,080 m)." },
      { day: "Day 4", title: "Explore Phu village", detail: "Rest day visiting Tashi Lhakhang Gompa and the old fort ruins." },
      { day: "Day 5", title: "Trek to Nar village", detail: "Descend and climb to the sister village of Nar (4,110 m)." },
      { day: "Day 6", title: "Acclimatization in Nar", detail: "Explore the village and nearby monasteries." },
      { day: "Day 7", title: "Trek to Kang La Phedi", detail: "Climb to the base camp for the Kang La Pass." },
      { day: "Day 8", title: "Cross Kang La to Ngawal", detail: "Cross Kang La Pass (5,320 m), rejoining the main Annapurna Circuit at Ngawal." },
      { day: "Day 9", title: "Trek to Manang", detail: "Continue to Manang (3,540 m) on the main circuit trail." },
      { day: "Day 10", title: "Trek to Yak Kharka", detail: "Begin the Thorong La approach." },
      { day: "Day 11", title: "Trek to Thorong Phedi", detail: "Climb to High Camp for the pass crossing." },
      { day: "Day 12", title: "Cross Thorong La to Muktinath", detail: "Cross Thorong La Pass (5,416 m) to Muktinath." },
      { day: "Day 13", title: "Drive to Pokhara", detail: "Drive via Jomsom and the Kali Gandaki valley to Pokhara." },
      { day: "Day 14", title: "Drive/fly to Kathmandu", detail: "Return to Kathmandu." },
      { day: "Day 15", title: "Departure", detail: "Transfer to the airport for your onward flight." },
    ],
    included: ["All ground transport", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits (Nar Phu RAP, ACAP)"],
    excluded: ["Meals in Kathmandu/Pokhara", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "Can Nar Phu Valley be combined with the full Annapurna Circuit?", a: "Yes — this is how we typically run it: entering the Nar Phu gorge from Koto, then rejoining the Annapurna Circuit at Ngawal via the Kang La Pass and continuing over Thorong La to Muktinath." },
    ],
  },
  {
    slug: "mohare-danda-khopra-ridge-trek",
    name: "Mohare Danda & Khopra Ridge Trek",
    region: "Annapurna Region",
    regionSlug: "annapurna",
    regionLabel: "Annapurna Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "Annapurna's quiet ridge trail, run as a community-tourism route",
    heroImage: "/images/treks/mardi-himal.jpg",
    gallery: ["/images/treks/mardi-himal.jpg"],
    duration: "12 Days",
    durationDays: 12,
    maxAltitude: "4,660 m / 15,289 ft (Khopra Ridge)",
    difficulty: "Moderate",
    bestSeason: "March–May & September–November",
    groupSize: "2–12 (private trips available)",
    priceFrom: 900,
    restrictedArea: false,
    shortDescription:
      "An off-the-beaten-path ridge trek through community-run lodges south of the Annapurna Sanctuary, with wide-open views of Dhaulagiri and Annapurna South from Khopra Ridge.",
    overview:
      "Developed as a community tourism initiative, the Mohare Danda and Khopra Ridge trek follows a quieter southern approach to the Annapurna range, staying in locally-run lodges built specifically to keep tourism income in the villages along the trail. The route climbs through rhododendron forest to open ridgelines at Mohare Danda and Khopra, delivering some of the widest uninterrupted views of Dhaulagiri, Annapurna South and Nilgiri in the region — with a fraction of the trekkers found on the nearby Poon Hill or ABC trails. An optional side trip reaches the sacred Khayer Lake.",
    highlights: [
      "Wide panoramic views of Dhaulagiri and the Annapurna Sanctuary peaks",
      "Community-owned lodges that keep tourism income local",
      "Far fewer trekkers than the nearby Poon Hill and ABC trails",
      "Optional side trip to the sacred, high-altitude Khayer Lake",
      "Rhododendron forest throughout the lower trail",
    ],
    permits: ["Annapurna Conservation Area Permit (ACAP)", "TIMS Card"],
    itinerary: [
      { day: "Day 1", title: "Drive Pokhara to Nayapul, trek to Tikhedhunga", detail: "Trailhead drive and first day's walk." },
      { day: "Day 2", title: "Trek to Ghorepani", detail: "Climb through rhododendron forest to Ghorepani (2,860 m)." },
      { day: "Day 3", title: "Trek to Mohare Danda", detail: "Branch off the main Poon Hill trail to Mohare Danda (3,300 m)." },
      { day: "Day 4", title: "Trek to Khopra", detail: "Continue along the ridge to Khopra (3,660 m)." },
      { day: "Day 5", title: "Day hike to Khayer Lake", detail: "Optional high-altitude side trip to the sacred lake (4,660 m)." },
      { day: "Day 6", title: "Trek to Swanta", detail: "Descend off the ridge toward Swanta village." },
      { day: "Day 7", title: "Trek to Ghandruk", detail: "Continue through Gurung villages to Ghandruk." },
      { day: "Day 8", title: "Trek to Nayapul, drive to Pokhara", detail: "Final descent and return drive to Pokhara." },
      { day: "Day 9–12", title: "Buffer / Pokhara leisure days", detail: "Contingency days for weather, or free time in Pokhara." },
    ],
    included: ["Pokhara–Nayapul–Pokhara transport", "Licensed trekking guide", "Porter service", "Community lodge accommodation", "All permits"],
    excluded: ["Kathmandu–Pokhara transport", "Meals outside the trek", "Travel insurance", "Tips"],
    faqs: [
      { q: "Why choose Khopra Ridge over Poon Hill?", a: "Khopra Ridge shares the same starting trail as Poon Hill but continues onto a much quieter ridge with arguably wider mountain views, staying in community-owned lodges that directly support the villages along the route." },
    ],
  },
  {
    slug: "tsum-valley-trek",
    name: "Tsum Valley Trek",
    region: "Manaslu Region",
    regionSlug: "manaslu",
    regionLabel: "Manaslu Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "A hidden valley of peace beside Manaslu",
    heroImage: "/images/treks/manaslu-circuit.jpg",
    gallery: ["/images/treks/manaslu-circuit.jpg"],
    duration: "16 Days",
    durationDays: 16,
    maxAltitude: "3,700 m / 12,139 ft (Mu Gompa)",
    difficulty: "Moderate",
    bestSeason: "March–May & September–November",
    groupSize: "Minimum 2 trekkers (restricted area regulation)",
    priceFrom: 1850,
    restrictedArea: true,
    shortDescription:
      "A restricted-area side valley off the Manaslu Circuit, historically known as a hidden Buddhist \"beyul\" (sacred valley) and home to centuries-old monasteries and a deeply preserved Tibetan culture.",
    overview:
      "Tsum Valley branches north from the lower Manaslu Circuit trail toward the Tibetan border, and was only opened to trekkers in 2008. Historically known as a beyul — a hidden valley of peace in Tibetan Buddhist tradition — Tsum remains one of the most culturally intact regions in Nepal, with ancient gompas, chortens and mani walls found at nearly every turn. Unlike the Manaslu Circuit itself, Tsum Valley does not require crossing a high pass, making it a genuinely moderate alternative for trekkers who want deep restricted-area culture without the altitude and technical demands of Larkya La.",
    highlights: [
      "A historic Buddhist \"beyul\" (hidden sacred valley) largely untouched by modern development",
      "Ancient monasteries including Mu Gompa and Rachen Gompa",
      "No high-pass crossing required — moderate difficulty for a restricted area",
      "Deeply preserved Tibetan Buddhist culture and architecture",
      "Can be combined with the full Manaslu Circuit for a longer trip",
    ],
    permits: ["Tsum Valley Restricted Area Permit", "Manaslu Conservation Area Permit (MCAP)"],
    itinerary: [
      { day: "Day 1", title: "Drive Kathmandu to Machha Khola", detail: "Long scenic drive to the trailhead." },
      { day: "Day 2", title: "Trek to Jagat", detail: "Follow the Budhi Gandaki gorge to Jagat." },
      { day: "Day 3", title: "Trek to Lokpa", detail: "Branch off the main Manaslu trail toward the Tsum valley." },
      { day: "Day 4", title: "Trek to Chumling", detail: "Enter Tsum Valley proper, first views of Ganesh Himal." },
      { day: "Day 5", title: "Trek to Chhokangparo", detail: "Continue up-valley through traditional villages." },
      { day: "Day 6", title: "Trek to Nile/Chhule", detail: "Walk past mani walls and chortens toward the upper valley." },
      { day: "Day 7", title: "Trek to Mu Gompa", detail: "Reach Mu Gompa (3,700 m), the valley's highest and most significant monastery." },
      { day: "Day 8", title: "Explore Mu Gompa and Dhephyudonma", detail: "Rest day exploring monasteries near the Tibet border." },
      { day: "Day 9", title: "Trek to Rachen Gompa", detail: "Descend to visit the nunnery at Rachen Gompa." },
      { day: "Day 10", title: "Trek to Chumling", detail: "Continue the descent back down the valley." },
      { day: "Day 11", title: "Trek to Lokpa", detail: "Rejoin the main Budhi Gandaki trail." },
      { day: "Day 12", title: "Trek to Jagat", detail: "Continue the descent." },
      { day: "Day 13", title: "Trek to Machha Khola", detail: "Final trekking day." },
      { day: "Day 14", title: "Drive to Kathmandu", detail: "Return drive to Kathmandu." },
      { day: "Day 15", title: "Kathmandu leisure day", detail: "Buffer day for road delays." },
      { day: "Day 16", title: "Departure", detail: "Transfer to the airport for your onward flight." },
    ],
    included: ["All ground transport", "Licensed trekking guide", "Porter service", "Teahouse accommodation", "All permits"],
    excluded: ["Meals in Kathmandu", "Travel insurance", "Personal gear", "Tips"],
    faqs: [
      { q: "Is Tsum Valley easier than the Manaslu Circuit?", a: "Yes — Tsum Valley doesn't require crossing a high pass like Larkya La, making it noticeably less physically demanding while still requiring the same restricted-area permits and guide arrangements." },
    ],
  },
  {
    slug: "kanchenjunga-circuit-trek",
    name: "Kanchenjunga Circuit Trek",
    region: "Kanchenjunga Region",
    regionSlug: "kanchenjunga",
    regionLabel: "Kanchenjunga Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "A remote circuit around the world's third-highest mountain",
    heroImage: "/images/gallery/kanchenjunga.jpg",
    gallery: ["/images/gallery/kanchenjunga.jpg"],
    duration: "22 Days",
    durationDays: 22,
    maxAltitude: "5,143 m / 16,873 ft (Sele La)",
    difficulty: "Strenuous",
    bestSeason: "March–May & September–November",
    groupSize: "Minimum 2 trekkers (restricted area regulation)",
    priceFrom: 2800,
    restrictedArea: true,
    shortDescription:
      "A long, remote restricted-area circuit around Kanchenjunga (8,586 m) in Nepal's far east, visiting both the north and south base camps through some of the least-visited wilderness in the country.",
    overview:
      "Kanchenjunga, the world's third-highest mountain, sits in Nepal's remote far-eastern corner near the Sikkim and Tibet borders — a region that sees only a fraction of the trekkers found in the Everest or Annapurna areas. The full circuit visits both the north and south base camp areas, crossing high passes and passing through Limbu and Rai villages, pristine rhododendron forest, and glacial valleys that feel genuinely undiscovered. This is a serious wilderness undertaking best suited to experienced trekkers with time for a long, remote itinerary.",
    highlights: [
      "Both north and south base camps of Kanchenjunga (8,586 m) on one trek",
      "One of Nepal's most remote and least-visited restricted areas",
      "Limbu and Rai villages found nowhere else in Nepal",
      "Genuine wilderness camping through pristine forest and glacial valleys",
      "Views of Kanchenjunga, Jannu and the eastern Himalayan skyline",
    ],
    permits: ["Kanchenjunga Restricted Area Permit", "Kanchenjunga Conservation Area Permit (KCAP)"],
    itinerary: [
      { day: "Day 1–2", title: "Fly Kathmandu to Bhadrapur, drive to Taplejung", detail: "Fly to the eastern lowlands, then drive up into the hills to the trailhead." },
      { day: "Day 3–5", title: "Trek to Sekathum and Amjilosa", detail: "Follow the Tamor river through Limbu villages into the lower valley." },
      { day: "Day 6–8", title: "Trek to Ghunsa", detail: "Continue up-valley through forest to the Tibetan-influenced village of Ghunsa (3,595 m)." },
      { day: "Day 9–10", title: "Trek to Kanchenjunga North Base Camp", detail: "Reach Pangpema for close-up views of Kanchenjunga's north face." },
      { day: "Day 11–13", title: "Cross Sele La to the south side", detail: "Cross the high pass (5,143 m) linking the north and south base camp valleys." },
      { day: "Day 14–16", title: "Trek to Kanchenjunga South Base Camp", detail: "Reach Oktang for views of the south face and Yalung Glacier." },
      { day: "Day 17–20", title: "Trek back to Taplejung", detail: "Long descent back through the lower valley villages." },
      { day: "Day 21–22", title: "Drive to Bhadrapur, fly to Kathmandu", detail: "Return flights back to Kathmandu." },
    ],
    included: ["All flights and ground transport", "Licensed trekking guide & camping crew", "Full camping equipment and meals during the trek", "All permits (RAP, KCAP)"],
    excluded: ["Meals in Kathmandu", "Travel insurance (incl. helicopter evacuation)", "Personal gear", "Tips"],
    faqs: [
      { q: "Do I need to visit both base camps?", a: "No — we can run a shorter itinerary to just the north or south base camp if 22 days isn't feasible, though the full circuit over Sele La is the classic, most complete version of this trek." },
    ],
  },
  {
    slug: "makalu-base-camp-trek",
    name: "Makalu Base Camp Trek",
    region: "Makalu Region",
    regionSlug: "makalu",
    regionLabel: "Makalu Region",
    categorySlug: "trekking",
    categoryLabel: "Trekking",
    tagline: "A wild approach to the world's fifth-highest mountain",
    heroImage: "/images/gallery/kanchenjunga.jpg",
    gallery: ["/images/gallery/kanchenjunga.jpg"],
    duration: "21 Days",
    durationDays: 21,
    maxAltitude: "5,250 m / 17,224 ft (Makalu Base Camp)",
    difficulty: "Strenuous",
    bestSeason: "March–May & September–November",
    groupSize: "Minimum 2 trekkers (restricted area regulation)",
    priceFrom: 2600,
    restrictedArea: true,
    shortDescription:
      "A remote wilderness trek through the Barun Valley to the base of Makalu (8,485 m), the world's fifth-highest peak, in one of Nepal's most biodiverse and least-trekked conservation areas.",
    overview:
      "The Makalu Base Camp Trek follows the Barun River through Makalu Barun National Park — a conservation area spanning tropical forest to high alpine terrain in the space of a single valley, home to red pandas, snow leopards and over 400 bird species. The trail sees very few trekkers compared to Nepal's more famous routes, climbing gradually through Sherpa and Rai villages before reaching the wild, glacier-lined amphitheatre at the foot of Makalu (8,485 m), the world's fifth-highest mountain. Camping is required for most of the route, as teahouse infrastructure remains minimal.",
    highlights: [
      "Base camp views of Makalu (8,485 m), the world's 5th-highest peak",
      "Makalu Barun National Park — forest to high alpine terrain in one valley",
      "Among the least-trekked major base camp routes in Nepal",
      "Genuine wilderness camping through pristine river valleys",
      "Rich biodiversity including red panda and snow leopard habitat",
    ],
    permits: ["Makalu Barun National Park Entry Permit", "Restricted Area Permit (for the upper valley)"],
    itinerary: [
      { day: "Day 1–2", title: "Fly Kathmandu to Tumlingtar, drive/trek to Num", detail: "Fly to the eastern lowlands and reach the trailhead." },
      { day: "Day 3–5", title: "Trek to Seduwa and Tashigaon", detail: "Follow the Arun and Barun valleys through Rai villages." },
      { day: "Day 6–8", title: "Trek to Khongma and Dobato", detail: "Climb into Makalu Barun National Park through rhododendron forest." },
      { day: "Day 9–11", title: "Trek to Yangle Kharka and Langmale", detail: "Enter the upper Barun valley, glaciers now visible ahead." },
      { day: "Day 12–13", title: "Trek to Makalu Base Camp", detail: "Reach the base camp (5,250 m) beneath Makalu's south face." },
      { day: "Day 14", title: "Explore Makalu Base Camp", detail: "Rest day with optional viewpoint hikes." },
      { day: "Day 15–19", title: "Trek back to Tashigaon and Num", detail: "Retrace the route back down the Barun valley." },
      { day: "Day 20–21", title: "Drive to Tumlingtar, fly to Kathmandu", detail: "Return flights back to Kathmandu." },
    ],
    included: ["All flights and ground transport", "Licensed trekking guide & camping crew", "Full camping equipment and meals during the trek", "All permits"],
    excluded: ["Meals in Kathmandu", "Travel insurance (incl. helicopter evacuation)", "Personal gear", "Tips"],
    faqs: [
      { q: "Is Makalu Base Camp harder than Everest Base Camp?", a: "In terms of physical demand and remoteness, yes — there is far less teahouse infrastructure, more camping is required, and the trail sees a fraction of the traffic, so self-sufficiency and prior trekking experience matter more here." },
    ],
  },
  {
    slug: "island-peak-climbing",
    name: "Island Peak Climbing",
    region: "Khumbu / Everest Region",
    regionSlug: "everest",
    regionLabel: "Everest Region",
    categorySlug: "peak-climbing",
    categoryLabel: "Peak Climbing",
    tagline: "The Khumbu's classic first Himalayan summit",
    heroImage: "/images/treks/everest-base-camp.jpg",
    gallery: ["/images/treks/everest-base-camp.jpg"],
    duration: "19 Days",
    durationDays: 19,
    maxAltitude: "6,189 m / 20,305 ft (Island Peak summit)",
    difficulty: "Strenuous",
    bestSeason: "March–May & September–November",
    groupSize: "2–8 (private trips available)",
    priceFrom: 2900,
    restrictedArea: false,
    shortDescription:
      "Nepal's most popular \"trekking peak\" — a genuine Himalayan summit above 6,000 m, combined with the classic approach through Everest Base Camp, using fixed ropes but no prior technical climbing experience required.",
    overview:
      "Island Peak (Imja Tse, 6,189 m) is the most climbed of Nepal's trekking peaks, prized for delivering a real Himalayan summit experience — including a headwall requiring fixed-rope jumar ascent — without demanding prior technical mountaineering experience. Our itinerary follows the classic Everest Base Camp approach through Namche and Dingboche before basing at Chhukung for the climb, giving proper acclimatization time before summit night. A qualified climbing Sherpa leads the technical sections and all climbing equipment is provided.",
    highlights: [
      "A genuine 6,189 m Himalayan summit — no prior technical climbing required",
      "Combines the classic Everest Base Camp trekking approach with a real climb",
      "Fixed-rope headwall climb under expert climbing Sherpa guidance",
      "Summit views of Everest, Lhotse, Makalu and Ama Dablam",
      "All climbing equipment and a pre-climb training day included",
    ],
    permits: ["Sagarmatha National Park Entry Permit", "Island Peak Climbing Permit (NMA)"],
    itinerary: [
      { day: "Day 1", title: "Arrive in Kathmandu", detail: "Airport pickup and climbing gear check." },
      { day: "Day 2", title: "Fly to Lukla, trek to Phakding", detail: "Flight to Lukla, short trek to Phakding." },
      { day: "Day 3", title: "Trek to Namche Bazaar", detail: "Climb to Namche Bazaar (3,440 m)." },
      { day: "Day 4", title: "Acclimatization in Namche", detail: "Day hike for altitude adjustment." },
      { day: "Day 5", title: "Trek to Tengboche", detail: "Walk to Tengboche Monastery." },
      { day: "Day 6", title: "Trek to Dingboche", detail: "Continue to Dingboche (4,410 m)." },
      { day: "Day 7", title: "Acclimatization in Dingboche", detail: "Hike to Nangkartshang viewpoint." },
      { day: "Day 8", title: "Trek to Chhukung", detail: "Short walk to Chhukung (4,730 m), the climb's base village." },
      { day: "Day 9", title: "Climbing training day", detail: "Practice with fixed ropes, jumar and crampons near Chhukung." },
      { day: "Day 10", title: "Trek to Island Peak Base Camp", detail: "Move up to base camp (5,087 m) beneath the peak." },
      { day: "Day 11", title: "Summit climb and descend to Chhukung", detail: "Pre-dawn summit push on Island Peak (6,189 m), descend same day." },
      { day: "Day 12", title: "Contingency day", detail: "Weather buffer for the summit attempt." },
      { day: "Day 13", title: "Trek to Dingboche", detail: "Rejoin the main EBC trail." },
      { day: "Day 14", title: "Trek to Namche Bazaar", detail: "Continue the descent." },
      { day: "Day 15", title: "Trek to Lukla", detail: "Final descent to Lukla." },
      { day: "Day 16", title: "Fly to Kathmandu", detail: "Morning flight back to Kathmandu." },
      { day: "Day 17", title: "Kathmandu buffer day", detail: "Contingency for flight delays." },
      { day: "Day 18", title: "Kathmandu leisure day", detail: "Free day for rest or sightseeing." },
      { day: "Day 19", title: "Departure", detail: "Transfer to the airport for your onward flight." },
    ],
    included: ["Airport transfers", "Kathmandu–Lukla–Kathmandu flights", "Licensed guide & climbing Sherpa", "Porter service", "Teahouse accommodation", "All climbing equipment and permits"],
    excluded: ["Nepal visa fee", "Travel insurance (incl. high-altitude rescue)", "Meals in Kathmandu", "Personal climbing clothing", "Tips"],
    faqs: [
      { q: "Do I need climbing experience for Island Peak?", a: "No prior technical climbing experience is required, but good physical fitness and prior high-altitude trekking experience are strongly recommended. Our climbing Sherpa trains you on the fixed ropes, jumar and crampons before the summit attempt." },
    ],
  },
  {
    slug: "mera-peak-climbing",
    name: "Mera Peak Climbing",
    region: "Khumbu / Everest Region",
    regionSlug: "everest",
    regionLabel: "Everest Region",
    categorySlug: "peak-climbing",
    categoryLabel: "Peak Climbing",
    tagline: "Nepal's highest trekking peak, and a five-8,000er summit view",
    heroImage: "/images/treks/everest-base-camp-3.jpg",
    gallery: ["/images/treks/everest-base-camp-3.jpg"],
    duration: "17 Days",
    durationDays: 17,
    maxAltitude: "6,461 m / 21,190 ft (Mera Peak summit)",
    difficulty: "Strenuous",
    bestSeason: "March–May & September–November",
    groupSize: "2–8 (private trips available)",
    priceFrom: 2600,
    restrictedArea: false,
    shortDescription:
      "The highest of Nepal's official trekking peaks, approached through the quiet Hinku valley, with a straightforward glacier walk to a summit offering views of five 8,000 m peaks including Everest.",
    overview:
      "At 6,461 m, Mera Peak is the highest of Nepal's classified \"trekking peaks,\" yet is technically more straightforward than Island Peak — mostly a glacier walk on moderate-angle snow slopes rather than a steep fixed-rope headwall, making it a good first true-altitude summit for fit trekkers. The approach through the remote, forested Hinku valley is a highlight in its own right, seeing far fewer trekkers than the main Khumbu trails, and the summit delivers one of the widest panoramas in Nepal — five 8,000 m peaks including Everest, Lhotse, Makalu, Kanchenjunga and Cho Oyu.",
    highlights: [
      "Nepal's highest trekking peak, with views of five 8,000 m mountains from the summit",
      "A quieter approach through the remote, forested Hinku valley",
      "Technically more straightforward than Island Peak — a glacier walk, not a headwall climb",
      "Genuine high-altitude mountaineering experience with full climbing support",
      "Crosses the Zatrwa La pass on the return route",
    ],
    permits: ["Makalu Barun National Park Entry Permit", "Mera Peak Climbing Permit (NMA)"],
    itinerary: [
      { day: "Day 1", title: "Arrive in Kathmandu", detail: "Airport pickup and climbing gear check." },
      { day: "Day 2", title: "Fly to Lukla, trek to Chutanga", detail: "Alternate flight/trailhead into the Hinku valley approach." },
      { day: "Day 3", title: "Cross Zatrwa La to Thuli Kharka", detail: "Cross the pass (4,610 m) into the Hinku valley." },
      { day: "Day 4", title: "Trek to Kothe", detail: "Descend into the forested Hinku valley." },
      { day: "Day 5", title: "Trek to Thangnak", detail: "Continue up-valley toward the glacier." },
      { day: "Day 6", title: "Acclimatization in Thangnak", detail: "Day hike to Dig Kharka viewpoint." },
      { day: "Day 7", title: "Trek to Khare", detail: "Reach Khare (5,045 m), the climb's staging village." },
      { day: "Day 8", title: "Climbing training day", detail: "Practice with crampons, ice axe and rope technique on the glacier." },
      { day: "Day 9", title: "Trek to Mera High Camp", detail: "Move up to High Camp (5,800 m)." },
      { day: "Day 10", title: "Summit climb and descend to Khare", detail: "Pre-dawn summit push on Mera Peak (6,461 m), descend same day." },
      { day: "Day 11", title: "Contingency day", detail: "Weather buffer for the summit attempt." },
      { day: "Day 12", title: "Trek to Kothe", detail: "Begin the descent back down the Hinku valley." },
      { day: "Day 13", title: "Trek to Thuli Kharka", detail: "Continue the descent." },
      { day: "Day 14", title: "Cross Zatrwa La to Lukla", detail: "Return crossing to Lukla." },
      { day: "Day 15", title: "Fly to Kathmandu", detail: "Morning flight back to Kathmandu." },
      { day: "Day 16", title: "Kathmandu buffer day", detail: "Contingency for flight delays." },
      { day: "Day 17", title: "Departure", detail: "Transfer to the airport for your onward flight." },
    ],
    included: ["Airport transfers", "Kathmandu–Lukla–Kathmandu flights", "Licensed guide & climbing Sherpa", "Porter service", "Teahouse/camping accommodation", "All climbing equipment and permits"],
    excluded: ["Nepal visa fee", "Travel insurance (incl. high-altitude rescue)", "Meals in Kathmandu", "Personal climbing clothing", "Tips"],
    faqs: [
      { q: "Is Mera Peak or Island Peak a better first climb?", a: "Mera Peak is technically easier (mostly a glacier walk) but reaches higher altitude; Island Peak is more technical (a steeper fixed-rope headwall) but slightly lower. We're happy to talk through which suits your fitness and goals." },
    ],
  },
  {
    slug: "chitwan-jungle-safari",
    name: "Chitwan Jungle Safari",
    region: "Chitwan National Park",
    regionSlug: "chitwan",
    regionLabel: "Chitwan",
    categorySlug: "jungle-safari",
    categoryLabel: "Jungle Safari",
    tagline: "One-horned rhinos, jungle walks and the Terai lowlands",
    heroImage: "/images/treks/mardi-himal.jpg",
    gallery: ["/images/treks/mardi-himal.jpg"],
    duration: "3 Days",
    durationDays: 3,
    maxAltitude: "150 m / 490 ft (Terai lowlands)",
    difficulty: "Easy",
    bestSeason: "October–March (dry season, best wildlife visibility)",
    groupSize: "2–16",
    priceFrom: 250,
    restrictedArea: false,
    shortDescription:
      "A short, easy escape from the mountains to Chitwan National Park's subtropical lowlands — jungle walks, a canoe ride and a strong chance of spotting the endangered one-horned rhino.",
    overview:
      "Chitwan National Park, a UNESCO World Heritage Site in Nepal's low-lying Terai region, protects one of the last strongholds of the greater one-horned rhinoceros along with Bengal tigers, gharial crocodiles and over 500 bird species. This short package is a popular add-on before or after a mountain trek — a complete change of scenery from alpine trails to dense sal forest and grassland, with guided jungle walks, a dugout canoe ride on the Rapti River, and visits to a nearby Tharu village to learn about the indigenous lowland culture.",
    highlights: [
      "A strong chance of spotting wild one-horned rhinoceros",
      "Guided jungle walks and a traditional dugout canoe ride",
      "A complete change of scenery from the mountains — subtropical forest and grassland",
      "Visit to a Tharu indigenous village and cultural program",
      "Easy, low-altitude trip suitable for all fitness levels",
    ],
    permits: ["Chitwan National Park Entry Permit"],
    itinerary: [
      { day: "Day 1", title: "Drive/fly to Chitwan, afternoon activities", detail: "Travel to Chitwan, afternoon village walk and cultural program." },
      { day: "Day 2", title: "Jungle walk, canoe ride and wildlife viewing", detail: "Full day of guided jungle activities and wildlife spotting." },
      { day: "Day 3", title: "Morning birdwatching, return to Kathmandu/Pokhara", detail: "Early activity before the return journey." },
    ],
    included: ["Ground transport", "National park permit and guide fees", "Lodge accommodation", "All meals during the safari"],
    excluded: ["Kathmandu/Pokhara transport if flying", "Travel insurance", "Personal expenses", "Tips"],
    faqs: [
      { q: "Is a rhino sighting guaranteed?", a: "No wildlife sighting can ever be guaranteed, but Chitwan has one of the highest rhino-encounter rates of any park in Asia — most guests see at least one during a 2–3 day visit." },
    ],
  },
  {
    slug: "kathmandu-valley-tour",
    name: "Kathmandu Valley Tour",
    region: "Kathmandu Valley",
    regionSlug: "kathmandu-valley",
    regionLabel: "Kathmandu Valley",
    categorySlug: "city-tour",
    categoryLabel: "City Tour",
    tagline: "Temples, stupas and living history in a single day",
    heroImage: "/images/brand/nepal-skyline-banner.png",
    gallery: ["/images/brand/nepal-skyline-banner.png"],
    duration: "1 Day",
    durationDays: 1,
    maxAltitude: "1,400 m / 4,593 ft (Kathmandu Valley)",
    difficulty: "Easy",
    bestSeason: "Year-round",
    groupSize: "1–20",
    priceFrom: 80,
    restrictedArea: false,
    shortDescription:
      "A full-day guided tour of Kathmandu's UNESCO World Heritage Sites — Pashupatinath, Boudhanath, Swayambhunath and Kathmandu Durbar Square — with a private vehicle and knowledgeable local guide.",
    overview:
      "Kathmandu Valley holds seven UNESCO World Heritage Sites within a few kilometres of each other, and this private day tour visits the four most essential: Pashupatinath Temple, the most sacred Hindu temple complex in Nepal; Boudhanath Stupa, one of the largest Buddhist stupas in the world and the heart of Kathmandu's Tibetan community; Swayambhunath (the \"Monkey Temple\"), an ancient hilltop stupa overlooking the whole valley; and Kathmandu Durbar Square, the historic royal palace complex. A great way to spend an arrival or departure day, or a rest day between treks.",
    highlights: [
      "Pashupatinath Temple, Nepal's most sacred Hindu site",
      "Boudhanath Stupa, the spiritual heart of Kathmandu's Tibetan community",
      "Swayambhunath (Monkey Temple) hilltop views over the whole valley",
      "Kathmandu Durbar Square's historic royal architecture",
      "Private vehicle and guide — flexible timing around your schedule",
    ],
    permits: ["Individual heritage site entry fees (included)"],
    itinerary: [
      { day: "Morning", title: "Pashupatinath Temple & Boudhanath Stupa", detail: "Visit the sacred Hindu temple complex, then the great Buddhist stupa nearby." },
      { day: "Afternoon", title: "Swayambhunath & Kathmandu Durbar Square", detail: "Hilltop stupa views, then the historic royal palace square." },
    ],
    included: ["Private vehicle and driver", "Licensed city guide", "All heritage site entry fees"],
    excluded: ["Meals", "Personal expenses", "Tips"],
    faqs: [
      { q: "Can this tour be combined with a trek?", a: "Yes — most guests run this as an add-on either the day after arriving (before flying to Lukla or driving to a trailhead) or as a rest day after a trek, and we can schedule it flexibly around your itinerary." },
    ],
  },
  {
    slug: "trishuli-river-rafting",
    name: "Trishuli River Rafting",
    region: "Trishuli River",
    regionSlug: "trishuli",
    regionLabel: "Trishuli River",
    categorySlug: "river-rafting",
    categoryLabel: "River Rafting",
    tagline: "Nepal's most accessible white-water day trip",
    heroImage: "/images/treks/langtang.jpg",
    gallery: ["/images/treks/langtang.jpg"],
    duration: "1 Day",
    durationDays: 1,
    maxAltitude: "550 m / 1,804 ft (river put-in point)",
    difficulty: "Easy",
    bestSeason: "September–June (best water levels; avoid peak monsoon)",
    groupSize: "2–16",
    priceFrom: 65,
    restrictedArea: false,
    shortDescription:
      "A short, exciting white-water rafting trip on the Trishuli River — Grade II–III rapids, easily combined with the drive to or from Kathmandu, and suitable for first-time rafters.",
    overview:
      "The Trishuli River is Nepal's most popular rafting destination, running alongside the main Kathmandu–Pokhara highway and offering Grade II–III rapids that are exciting for first-timers without requiring prior rafting experience. It's easy to combine with a Kathmandu–Pokhara drive (stopping to raft a section along the way) or run as a standalone half or full-day trip from Kathmandu. All safety equipment, an experienced river guide, and a safety kayak are included on every trip.",
    highlights: [
      "Grade II–III rapids — exciting but approachable for first-time rafters",
      "Easily combined with the Kathmandu–Pokhara road journey",
      "All safety equipment and an experienced river guide included",
      "Scenic river gorge scenery along the Trishuli valley",
      "Available as a half-day or full-day trip",
    ],
    permits: ["No special permit required"],
    itinerary: [
      { day: "Morning", title: "Drive to the put-in point and safety briefing", detail: "Transfer to the river, fitted for safety gear, and briefed on rafting technique." },
      { day: "Midday–Afternoon", title: "Raft the Trishuli's rapids", detail: "Several hours on the river running Grade II–III rapids with your guide." },
    ],
    included: ["Rafting equipment (raft, paddle, helmet, life jacket)", "Experienced river guide and safety kayaker", "Lunch on the riverbank"],
    excluded: ["Transport to/from Kathmandu (unless combined with a Pokhara transfer)", "Travel insurance", "Tips"],
    faqs: [
      { q: "Do I need rafting experience?", a: "No — the Trishuli's Grade II–III rapids are considered a good introduction to white-water rafting, and our guides give a full safety briefing before you get on the water." },
    ],
  },
];

export function getTrekBySlug(slug: string) {
  return treks.find((t) => t.slug === slug);
}

export function getRelatedTreks(slug: string, count = 3) {
  const current = getTrekBySlug(slug);
  if (!current) return treks.slice(0, count);
  return treks
    .filter((t) => t.slug !== slug)
    .sort((a, b) => {
      const aRegion = a.regionSlug === current.regionSlug ? 0 : 1;
      const bRegion = b.regionSlug === current.regionSlug ? 0 : 1;
      return aRegion - bRegion;
    })
    .slice(0, count);
}

export function getTreksByRegion(regionSlug: string) {
  return treks.filter((t) => t.regionSlug === regionSlug);
}

export function getRegionBySlug(regionSlug: string) {
  return regions.find((r) => r.slug === regionSlug);
}

export function getTreksGroupedByRegion() {
  return regions.map((region) => ({
    ...region,
    treks: treks.filter((t) => t.regionSlug === region.slug),
  }));
}

export function getTreksByCategory(categorySlug: string) {
  return treks.filter((t) => t.categorySlug === categorySlug);
}
